name:  Upload Ubuntu 22.04 java tool cache

on:
  workflow_dispatch:

jobs:
  upload_tool_cache:
    runs-on: ubuntu-22.04
    steps:
      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'
          java-package: jdk # optional (jdk or jre) - defaults to jdk
  
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew  

      - name: Archive tool cache
        run: |
          cd "${{ runner.tool_cache }}"
          tar -czf tool_cache_ubuntu_java.tar.gz *
      - name: Upload tool cache artifact
        uses: actions/upload-artifact@v3
        with:
          path: ${{runner.tool_cache}}/tool_cache_ubuntu_java.tar.gz
